# Day 2: NumPy基礎 - 配列・行列操作

## 学習目標
- NumPyの基本的な使い方を理解する
- 配列の作成、操作、変形を習得する
- 行列演算の基本を理解する
- 統計関数の使い方を学ぶ

## 1. NumPyのインポートと基本

In [1]:
import numpy as np

# NumPyのバージョン確認
print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.2


In [2]:
import numpy as np

print(f"Numpy version: {np.__version__}")

Numpy version: 2.3.2


## 2. 配列の作成

In [3]:
# リストから配列を作成
arr1 = np.array([1, 2, 3, 4, 5])
print("1次元配列:", arr1)
print("型:", arr1.dtype)
print("形状:", arr1.shape)
print("次元数:", arr1.ndim)
print("要素数:", arr1.size)

1次元配列: [1 2 3 4 5]
型: int64
形状: (5,)
次元数: 1
要素数: 5


In [4]:
# 2次元配列（行列）の作成
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
print("2次元配列:\n", arr2)
print("形状:", arr2.shape)  # (行数, 列数)

2次元配列:
 [[1 2 3]
 [4 5 6]]
形状: (2, 3)


In [6]:
# 特殊な配列の作成
zeros = np.zeros((3, 4))  # 3x4のゼロ行列
ones = np.ones((2, 3))    # 2x3の1で埋められた行列
eye = np.eye(3)           # 3x3の単位行列

print("ゼロ行列:\n", zeros)
print("\n1で埋められた行列:\n", ones)
print("\n単位行列:\n", eye)

ゼロ行列:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

1で埋められた行列:
 [[1. 1. 1.]
 [1. 1. 1.]]

単位行列:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
zeros = np.zeros((5,4))
ones = np.ones((5,4))
eye = np.eye(5)

print("ゼロ行列:\n",zeros)
print("\n1で埋められた行列:\n", ones)
print("\n単位行列:\n", eye)

ゼロ行列:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

1で埋められた行列:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

単位行列:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
# 連続した値を持つ配列
arange = np.arange(0, 10, 2)  # 0から10まで2刻み
linspace = np.linspace(0, 1, 5)  # 0から1まで5等分

print("arange:", arange)
print("linspace:", linspace)

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


In [24]:
# ランダムな配列
np.random.seed(42)  # 再現性のためのシード設定
rand_uniform = np.random.rand(3, 3)  # 0-1の一様分布
rand_normal = np.random.randn(3, 3)  # 標準正規分布
rand_int = np.random.randint(1, 10, size=(3, 3))  # 1-9の整数

print("一様分布:\n", rand_uniform)
print("\n正規分布:\n", rand_normal)
print("\n整数乱数:\n", rand_int)

一様分布:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

正規分布:
 [[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]

整数乱数:
 [[3 7 4]
 [9 3 5]
 [3 7 5]]


## 3. 配列の操作とインデックス

In [18]:
# 1次元配列のインデックスとスライス
arr = np.array([10, 20, 30, 40, 50])
print("元の配列:", arr)
print("最初の要素:", arr[0])
print("最後の要素:", arr[-1])
print("2番目から4番目:", arr[1:4])
print("逆順:", arr[::-1])

元の配列: [10 20 30 40 50]
最初の要素: 10
最後の要素: 50
2番目から4番目: [20 30 40]
逆順: [50 40 30 20 10]


In [19]:
# 2次元配列のインデックス
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("行列:\n", mat)
print("\n要素(1,2):", mat[1, 2])  # 2行3列目の要素
print("\n2行目全体:", mat[1, :])
print("\n2列目全体:", mat[:, 1])
print("\n部分行列:\n", mat[0:2, 1:3])

行列:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

要素(1,2): 6

2行目全体: [4 5 6]

2列目全体: [2 5 8]

部分行列:
 [[2 3]
 [5 6]]


In [20]:
# 条件によるインデックス（ブールインデックス）
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3
print("条件マスク:", mask)
print("3より大きい要素:", arr[mask])

# 直接条件を使用
print("偶数の要素:", arr[arr % 2 == 0])

条件マスク: [False False False  True  True  True]
3より大きい要素: [4 5 6]
偶数の要素: [2 4 6]


## 4. 配列の形状変更

In [21]:
# reshape
arr = np.arange(12)
print("元の配列:", arr)

# 様々な形状に変更
reshaped_3x4 = arr.reshape(3, 4)
reshaped_2x6 = arr.reshape(2, 6)
reshaped_auto = arr.reshape(3, -1)  # -1は自動計算

print("\n3x4に変形:\n", reshaped_3x4)
print("\n2x6に変形:\n", reshaped_2x6)
print("\n3x?に変形（自動）:\n", reshaped_auto)

元の配列: [ 0  1  2  3  4  5  6  7  8  9 10 11]

3x4に変形:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

2x6に変形:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

3x?に変形（自動）:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
# flatten と ravel
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("元の行列:\n", mat)

flattened = mat.flatten()  # コピーを作成
raveled = mat.ravel()      # ビューを作成（可能な場合）

print("\nflatten:", flattened)
print("ravel:", raveled)

元の行列:
 [[1 2 3]
 [4 5 6]]

flatten: [1 2 3 4 5 6]
ravel: [1 2 3 4 5 6]


## latten() と ravel() の目的
これらのメソッドは多次元配列を1次元配列に変換するためのものです。「平坦化（flattening）」と呼ばれる操作で、2次元配列を1次元に「潰す」のが目的なんです。

## なぜ1次元になるのか？
2次元配列 [[1, 2, 3], [4, 5, 6]] は、メモリ上では実際には [1, 2, 3, 4, 5, 6] として連続して格納されています。flatten() と ravel() はその「本来の姿」を見せているとも言えます。

In [25]:
# 転置
mat = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("元の行列 (2x3):\n", mat)
print("\n転置行列 (3x2):\n", mat.T)
print("\nnp.transposeを使用:\n", np.transpose(mat))

元の行列 (2x3):
 [[1 2 3]
 [4 5 6]]

転置行列 (3x2):
 [[1 4]
 [2 5]
 [3 6]]

np.transposeを使用:
 [[1 4]
 [2 5]
 [3 6]]


1. どちらを使うべき？
一般的には mat.T を使うことが多いです：
pythonimport numpy as np

mat = np.array([[1, 2, 3], [4, 5, 6]])

# 推奨：簡潔で読みやすい
result1 = mat.T

# こちらも正しいが、やや冗長
result2 = np.transpose(mat)
使い分けの目安：

2次元配列: mat.T が簡潔で一般的
3次元以上で軸を指定したい場合: np.transpose() を使用

python# 3次元配列で軸を指定する場合
arr_3d = np.random.rand(2, 3, 4)
# 軸を指定できるのはnp.transpose()のみ
result = np.transpose(arr_3d, (2, 0, 1))  # 軸の順番を変更
2. Tはtransposeの略？
はい、その通りです！ .T は "transpose" の略です。
3. 実際の値は入れ替わっていない？
正解です！ これは重要なポイントです：
pythonimport numpy as np

mat = np.array([[1, 2, 3], [4, 5, 6]])
print("元の配列:\n", mat)

# 転置はビュー（view）を作成するだけ
transposed = mat.T
print("転置後も元の配列は変わらない:\n", mat)

# ただし、転置したビューを変更すると元の配列も変わる！
transposed[0, 0] = 999
print("転置ビューを変更後の元の配列:\n", mat)
出力：
元の配列:
 [[1 2 3]
 [4 5 6]]

転置後も元の配列は変わらない:
 [[1 2 3]
 [4 5 6]]

転置ビューを変更後の元の配列:
 [[999   2   3]
 [  4   5   6]]
ビューとコピーの確認方法
pythonmat = np.array([[1, 2, 3], [4, 5, 6]])
transposed = mat.T

# 同じメモリを共有しているか確認
print("同じメモリを共有:", np.shares_memory(mat, transposed))  # True

# もしコピーが欲しい場合
transposed_copy = mat.T.copy()
print("コピーとはメモリを共有しない:", np.shares_memory(mat, transposed_copy))  # False
まとめ：

mat.T は簡潔で推奨
実際の配列は変更されず、ビューが作成される
ビューを変更すると元の配列も変わるので注意！
再試行Claudeは間違えることがあります。回答内容を必ずご確認ください。リサーチ Sonnet 4

## 5. 配列の演算

In [26]:
# 要素ごとの演算
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("a:", a)
print("b:", b)
print("\n加算 (a + b):", a + b)
print("減算 (a - b):", a - b)
print("乗算 (a * b):", a * b)
print("除算 (a / b):", a / b)
print("べき乗 (a ** 2):", a ** 2)

a: [1 2 3 4]
b: [5 6 7 8]

加算 (a + b): [ 6  8 10 12]
減算 (a - b): [-4 -4 -4 -4]
乗算 (a * b): [ 5 12 21 32]
除算 (a / b): [0.2        0.33333333 0.42857143 0.5       ]
べき乗 (a ** 2): [ 1  4  9 16]


In [27]:
# スカラーとの演算
arr = np.array([[1, 2], [3, 4]])
print("元の配列:\n", arr)
print("\n全要素に10を加算:\n", arr + 10)
print("\n全要素を2倍:\n", arr * 2)

元の配列:
 [[1 2]
 [3 4]]

全要素に10を加算:
 [[11 12]
 [13 14]]

全要素を2倍:
 [[2 4]
 [6 8]]


In [28]:
# 行列積
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])

print("行列A:\n", A)
print("\n行列B:\n", B)
print("\n要素ごとの積 (A * B):\n", A * B)
print("\n行列積 (A @ B):\n", A @ B)
print("\nnp.dotを使用:\n", np.dot(A, B))

行列A:
 [[1 2]
 [3 4]]

行列B:
 [[5 6]
 [7 8]]

要素ごとの積 (A * B):
 [[ 5 12]
 [21 32]]

行列積 (A @ B):
 [[19 22]
 [43 50]]

np.dotを使用:
 [[19 22]
 [43 50]]


In [29]:
# ブロードキャスティング
# 異なる形状の配列間での演算
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
row_vec = np.array([10, 20, 30])
col_vec = np.array([[100], [200], [300]])

print("行列:\n", mat)
print("\n行ベクトル:", row_vec)
print("\n列ベクトル:\n", col_vec)
print("\n行列 + 行ベクトル:\n", mat + row_vec)
print("\n行列 + 列ベクトル:\n", mat + col_vec)

行列:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

行ベクトル: [10 20 30]

列ベクトル:
 [[100]
 [200]
 [300]]

行列 + 行ベクトル:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

行列 + 列ベクトル:
 [[101 102 103]
 [204 205 206]
 [307 308 309]]


## 6. 統計関数と集約関数

In [30]:
# 基本的な統計関数
data = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15]])

print("データ:\n", data)
print("\n全体の統計:")
print(f"合計: {np.sum(data)}")
print(f"平均: {np.mean(data):.2f}")
print(f"標準偏差: {np.std(data):.2f}")
print(f"分散: {np.var(data):.2f}")
print(f"最小値: {np.min(data)}")
print(f"最大値: {np.max(data)}")

データ:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

全体の統計:
合計: 120
平均: 8.00
標準偏差: 4.32
分散: 18.67
最小値: 1
最大値: 15


In [31]:
# 軸に沿った集約
print("各列の合計 (axis=0):", np.sum(data, axis=0))
print("各行の合計 (axis=1):", np.sum(data, axis=1))
print("\n各列の平均:", np.mean(data, axis=0))
print("各行の平均:", np.mean(data, axis=1))

各列の合計 (axis=0): [18 21 24 27 30]
各行の合計 (axis=1): [15 40 65]

各列の平均: [ 6.  7.  8.  9. 10.]
各行の平均: [ 3.  8. 13.]


In [32]:
# その他の便利な関数
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("配列:", arr)
print("\n累積和:", np.cumsum(arr))
print("累積積:", np.cumprod(arr))
print("\n最大値のインデックス:", np.argmax(arr))
print("最小値のインデックス:", np.argmin(arr))
print("\nソート済み:", np.sort(arr))
print("ソートのインデックス:", np.argsort(arr))

配列: [3 1 4 1 5 9 2 6]

累積和: [ 3  4  8  9 14 23 25 31]
累積積: [   3    3   12   12   60  540 1080 6480]

最大値のインデックス: 5
最小値のインデックス: 1

ソート済み: [1 1 2 3 4 5 6 9]
ソートのインデックス: [1 3 6 0 2 4 7 5]


## 7. 実践演習

### 演習1: 行列の基本操作
以下の要件を満たすコードを書いてください：
1. 5×5の単位行列を作成
2. その対角要素を[1, 2, 3, 4, 5]に変更
3. 結果を表示

In [36]:
# 演習1の解答
# ここにコードを書いてください
mat = np.eye(5)
np.fill_diagonal(mat, [1,2,3,4,5])
print("対角要素を変更した行列：\n", mat)

対角要素を変更した行列：
 [[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


### 演習2: データ分析
1. 平均50、標準偏差10の正規分布から100個のデータを生成
2. データの基本統計量（平均、標準偏差、最小、最大）を計算
3. 60以上の値の個数を数える

In [37]:
# 演習2の解答
# ここにコードを書いてください
np.random.seed(42)
data = np.random.normal(50, 10, 100)

print(f"平均: {np.mean(data):.2f}")
print(f"標準偏差: {np.std(data):.2f}")
print(f"最小値: {np.min(data):.2f}")
print(f"最大値: {np.max(data):.2f}")
print(f"60以上の値の個数: {np.sum(data >= 60)}")

平均: 48.96
標準偏差: 9.04
最小値: 23.80
最大値: 68.52
60以上の値の個数: 11


### 演習3: 画像データのシミュレーション
1. 28×28のランダムな「画像」（0-255の整数値）を作成
2. 画像を上下反転
3. 画像を90度回転
4. 画像の明るさを調整（全ピクセルの値を0.5倍）

In [38]:
# 演習3の解答
# ここにコードを書いてください
np.random.seed(42)
image = np.random.randint(0, 256, size=(28, 28))
print("元の画像の形状:", image.shape)
print("最初の5x5ピクセル:\n", image[:5, :5])

# 上下反転
flipped = np.flipud(image)
# または image[::-1, :]

# 90度回転（反時計回り）
rotated = np.rot90(image)

# 明るさ調整
darkened = (image * 0.5).astype(int)

print("\n処理後の画像の統計:")
print(f"明るさ調整前の平均: {np.mean(image):.2f}")
print(f"明るさ調整後の平均: {np.mean(darkened):.2f}")

元の画像の形状: (28, 28)
最初の5x5ピクセル:
 [[102 179  92  14 106]
 [191 187  20 160 203]
 [ 63 248 130 228  50]
 [174  34 205  80 163]
 [199 205 214 251 248]]

処理後の画像の統計:
明るさ調整前の平均: 132.38
明るさ調整後の平均: 65.93


## 演習の解答例

In [ ]:
# 演習1の解答例
mat = np.eye(5)
np.fill_diagonal(mat, [1, 2, 3, 4, 5])
print("対角要素を変更した行列:\n", mat)

In [ ]:
# 演習2の解答例
np.random.seed(42)
data = np.random.normal(50, 10, 100)

print(f"平均: {np.mean(data):.2f}")
print(f"標準偏差: {np.std(data):.2f}")
print(f"最小値: {np.min(data):.2f}")
print(f"最大値: {np.max(data):.2f}")
print(f"60以上の値の個数: {np.sum(data >= 60)}")

In [ ]:
# 演習3の解答例
np.random.seed(42)
image = np.random.randint(0, 256, size=(28, 28))
print("元の画像の形状:", image.shape)
print("最初の5x5ピクセル:\n", image[:5, :5])

# 上下反転
flipped = np.flipud(image)
# または image[::-1, :]

# 90度回転（反時計回り）
rotated = np.rot90(image)

# 明るさ調整
darkened = (image * 0.5).astype(int)

print("\n処理後の画像の統計:")
print(f"明るさ調整前の平均: {np.mean(image):.2f}")
print(f"明るさ調整後の平均: {np.mean(darkened):.2f}")

## まとめ

今日学んだこと：
1. **配列の作成**: array, zeros, ones, arange, linspace, random
2. **インデックスとスライス**: 基本的なインデックス、ブールインデックス
3. **形状変更**: reshape, flatten, transpose
4. **演算**: 要素ごとの演算、行列積、ブロードキャスティング
5. **統計関数**: sum, mean, std, min, max とその軸指定

NumPyは機械学習やデータ分析の基礎となるライブラリです。
これらの操作を習得することで、より複雑なデータ処理が可能になります。